# name: Deploy To Huawei Cloud 

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy To Huawei Cloud
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           port: ${{ secrets.SSH_PORT }}
#           password: ${{ secrets.SSH_PASSWORD }}
#           script: |
#             cd /var/www/misterlalusin.github.io
#             git checkout master
#             git pull origin master